// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlc

import (
	"time"

	custom_types "github.com/expoure/pismo/transaction/internal/configuration/database/custom_types"
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OperationType struct {
	ID          int32
	Description string
}

type Transaction struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	OperationTypeID pgtype.Int4
	Amount          custom_types.Money
	EventDate       time.Time
}
