// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlc

import (
	"database/sql"
	"time"

	custom_types "github.com/expoure/pismo/transaction/internal/configuration/database/custom_types"
	"github.com/google/uuid"
)

type OperationType struct {
	ID          int32
	Description string
}

type Transaction struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	OperationTypeID sql.NullInt32
	Amount          *custom_types.Money
	EventDate       time.Time
}
