// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlc

import (
	"time"

	custom_types "github.com/expoure/pismo/account/internal/configuration/database/custom_types"
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             uuid.UUID
	DocumentNumber string
	Balance        *custom_types.Money
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
}
