// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlc

import (
	"context"

	custom_types "github.com/expoure/pismo/account/internal/configuration/database/custom_types"
	uuid "github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, documentNumber string) (Account, error)
	FindAccountBalanceById(ctx context.Context, id uuid.UUID) (*custom_types.Money, error)
	FindAccountByDocumentNumber(ctx context.Context, documentNumber string) (Account, error)
	FindAccountById(ctx context.Context, id uuid.UUID) (Account, error)
}

var _ Querier = (*Queries)(nil)
